verdaccio/ui

- src/webui/components/ActionBar/index.js
- src/webui/components/CopyToClipBoard/index.js
- src/webui/components/Dependencies/index.js
- src/webui/components/DetailSidebar/index.js
- src/webui/components/Developers/index.js
- src/webui/components/Dist/index.js
- src/webui/components/Engines/index.js
- src/webui/components/Footer/styles.js
- src/webui/utils/styles/colors.js
- tools/verdaccio.js
Type: refactor
Description:
- Fixes name spacing and eslint issues.
> refactor: corrects eslint and variable name spacing

- README.md
- src/webui/template/index.html
- src/webui/utils/styles/colors.js
- tools/webpack.prod.config.babel.js
**Type:** Feature
- Issue: https://github.com/verdaccio/ui/issues/11
- Corresponding PR: https://github.com/verdaccio/verdaccio/pull/1282
> Accept primary color to be configured

- .github/main.workflow
- scripts/build-test.sh
**Type:** Chore
- Adds PR workflow
- improves old actions
> adds pull request action

- src/webui/components/Versions/index.js
**Type:** Bug
*  There is a related issue? Yes
@juanpicado  Please test this with `@juan/pkg1` from our package database.
> fix: version rendering issue. 

- .github/main.workflow
**Type:** Chore
- Updates existing Github actions workflow
> chore: adds actions

- package.json
- src/components/Developers/__snapshots__/Developers.test.tsx.snap
- yarn.lock
**Type:** Chore
**The following has been addressed in the PR:** There is no issue for this PR
Removed the dependency @material-ui/styles, because it wasn't being used and pumped @material-ui/core and @material-ui/icons
> Chore: pumped mui version

- src/App/App.tsx
- src/styles/typeface-roboto.css
- tools/webpack.config.js
**Type:**
bug
This should fix the wrong paths for the Roboto fonts.
Resolves #128
> fix: correctly load font files - closes #128

- README.md
**Type:**
docs
This PR removes the dead link to CONTRIBUTING.md.
> docs: remove contributing link

- src/App/App.tsx
- src/components/ActionBar/ActionBar.test.tsx
- src/components/ActionBar/ActionBar.tsx
- src/components/Dependencies/Dependencies.tsx
- src/components/Developers/Developers.tsx
- src/components/Engines/Engines.test.tsx
- src/components/Footer/Footer.test.tsx
- src/components/Footer/Footer.tsx
- src/components/Footer/styles.ts
- src/components/Header/Header.tsx
- src/components/Header/styles.ts
- src/components/Icon/Icon.tsx
- src/components/Label/Label.tsx
- src/components/Layout/Layout.tsx
- src/components/Package/Package.tsx
- src/components/Package/styles.ts
- src/components/Repository/Repository.test.tsx
- src/components/Spinner/Spinner.tsx
- src/components/Spinner/styles.ts
- src/utils/api.ts
- src/utils/styles/colors.ts
- src/utils/styles/media.ts
- types/index.ts
**Type:**
* A few `@ts-ignore` directives have been removed
- Removed many unnecessary @ts-ignore
- Add typings for emotion components
- Improve typings for jest mocks
- Fix media query typings
Resolves #151
> Fix a few ts-ignore

- src/components/UpLinks/UpLinks.test.tsx
- src/components/UpLinks/UpLinks.tsx
- src/components/UpLinks/__snapshots__/UpLinks.test.tsx.snap
*  There is a related issue? Nope
*  Unit or Functional tests are included in the PR: Yes
> Uplinks - Replaced class by func. comp

- src/components/Versions/Versions.tsx
- types/packageMeta.ts
> Fix: dist-tags attribute spelling error

- src/components/Spinner/styles.ts
- src/muiComponents/CircularProgress/CircularProgress.tsx
- src/muiComponents/CircularProgress/index.ts
**The following has been addressed in the PR:** #162
**Unit or Functional tests are included in the PR?**  Not yet
Wrapped Material UI CirularProgress Component with ForwardRef
> CircularProgress Component - Introduced ForwardRef

- src/components/Login/Login.tsx
- src/components/RegistryInfoDialog/RegistryInfoDialog.tsx
- src/components/RegistryInfoDialog/styles.ts
- src/muiComponents/Dialog/Dialog.tsx
- src/muiComponents/Dialog/index.ts
- src/muiComponents/DialogActions/DialogActions.tsx
- src/muiComponents/DialogActions/index.ts
- src/muiComponents/DialogContent/DialogContent.tsx
- src/muiComponents/DialogContent/index.ts
- src/muiComponents/DialogTitle/DialogTitle.tsx
- src/muiComponents/DialogTitle/index.ts
- src/pages/Version/styles.ts
**The following has been addressed in the PR:** #162
Wrapped Material UI Dialog, DialogTitle, DialogActions and DialogContent Components with ForwardRef.
> Dialog Components - Introduced ForwardRef

- src/icons/GitHub.tsx
- src/muiComponents/SvgIcon/SvgIcon.tsx
- src/muiComponents/SvgIcon/index.ts
**The following has been addressed in the PR:** #162
Wrapped Material UI SvgIcon Component with ForwardRef.
> SvgIcon Component - Introduced ForwardRef

- src/components/Install/InstallListItem.tsx
**Type:**
bug
*  There is a related issue? https://github.com/verdaccio/ui/issues/208
*  Unit or Functional tests are included in the PR : 
It seems the snapshot is working fine with making these changes.
please let me know if this required changing the tests
Swapped the icon-svg.
> fix(installItemList): changed the wrong icon

- src/components/NotFound/NotFound.tsx
- src/components/NotFound/Notfound.test.tsx
**Type:** unit test
*  Unit or Functional tests are included in the PR Yes
adds missing test spec for button click in not found
> refactor: adds missing test spec for button click in not found

- jest/jestEnvironment.js
- jest/setup.ts
- src/utils/url.test.ts
- src/utils/url.ts
> Revert "fix: correctly reference registry url from options"

- src/components/ActionBar/__snapshots__/ActionBar.test.tsx.snap
**Type:** Fix
Updated ActionBar component snapshot
> Fix: updated actionbar snap

- src/utils/package.ts
**Type:** Fix
Removed an unused import
> Fix: removed dead import

- package.json
- src/App/__snapshots__/App.test.tsx.snap
- yarn.lock
**Type:** Chore
**Description:**  bump @material-ui/core from 4.7.2 to 4.8.0
> Chore: bump @material-ui/core from 4.7.2 to 4.8.0

- src/App/App.tsx
**Type:**
bugfix
*  Prevent double padding by rmeoving it
*  Add missing background color
Resolves #373
> fix: remove double padding and add missing background color - closes #373

- src/components/Install/InstallListItem.tsx
- src/components/Repository/Repository.tsx
**Type:**
bugfix
*  Remove background from a few styled `Avatar` components.
Resolves #371
> fix: remove background from styled Avatar components - closes #371

- README.md
> ref(readme): added i18n section 

- CHANGELOG.md
- package.json
> fix(chore): droped release

- README.md
Added a step by step of how to add a new language
> ref(doc): updated translation section

- .secrets-baseline
- README.md
**Type:** Fix
Replaced cs-cz with czech
> ref(doc): replaced cs_cz with czech

- .vscode/settings.json
By saving the file, not all prettier errors were being fixed. This PR fixes the problem.
> ref(setting): Fixed settings eslint autofix on save

- .eslintrc
- i18n/translations/de-DE.json
- i18n/translations/en-US.json
- i18n/translations/es-ES.json
- i18n/translations/fr-FR.json
- i18n/translations/ja-JP.json
- i18n/translations/km-KH.json
- i18n/translations/pt-BR.json
- i18n/translations/uk-UA.json
- i18n/translations/zh-CN.json
- src/App/__snapshots__/App.test.tsx.snap
- src/components/AutoComplete/AutoComplete.tsx
- src/components/AutoComplete/AutoCompleteV2.tsx
- src/components/AutoComplete/useAutoComplete.tsx
- src/components/Header/__snapshots__/Header.test.tsx.snap
- src/components/LanguageSwitch/LanguageSwitch.tsx
- src/design-tokens/ThemeProvider.tsx
- src/design-tokens/useOnClickOutside.ts
> ref(ui): Updated autocomplete

- i18n/translations/zh-CN.json
**Type:** Translation
**Description:** Improve Chinese translation : )
> feat(i18n): Improve Chinese(zh-CN) translation

- .github/workflows/codeql-analysis.yml
We have access to https://github.com/features/security
> build: enable code scan security

- package.json
- src/design-tokens/ResetStyles.tsx
- src/pages/home/PackageList/Package/Package.tsx
- src/pages/home/PackageList/Package/styles.ts
- src/pages/home/PackageList/PackageList.tsx
- src/pages/home/PackageList/Packagelist.test.tsx
- yarn.lock
**Type:** Feat
The following has been addressed in the PR: https://github.com/verdaccio/ui/pull/172
*  There is a related issue? https://github.com/verdaccio/verdaccio/issues/1403
*  Unit or Functional tests are included in the PR: Not yet
After some research, we decided to use the library `react-virtualized`, which despite being large, seems more stable, being maintained by several contributors and used in many different projects and companies.
This PR introduces this library to the `PackageList` component. The list is now being virtualized, providing better performance when rendering a large number of items.
The implementation has some limitations. If the user performs a fast scrolling, some blank white spaces will be shown. This issue seems to be a well-knowen issue …
> Feat(packagelist): Add list windowing

- i18n/translations/es-ES.json
Changed some words improving the Spanish translation, also added some accent marks.
**Type:**
*  There is a related issue? No. 
*  Unit or Functional tests are included in the PR? No. 
Happier spanish speaking users.
> Changed some words to improve Spanish translation

- src/App/Header/__snapshots__/Header.test.tsx.snap
- src/App/Header/styles.ts
- src/App/__snapshots__/App.test.tsx.snap
**Type:**
refactor
remove max-width: 393px to make the reactive area more wide
#559
> refactor: change the search input style

- src/App/Header/Search/__snapshots__/Search.test.tsx.snap
- src/App/Header/__snapshots__/Header.test.tsx.snap
- src/App/__snapshots__/App.test.tsx.snap
- src/components/AutoComplete/styles.tsx
Now, when the user hovers over the search bar, the white border is displayed
>  ref(searchbar): Add Searchbar minor adjusts

- src/pages/Version/DetailSidebar/Developers/DevelopersTitle.tsx
**Type: linting**
*  Unit or Functional tests are included in the PR? No
Removes lint warnings from DevelopersTitle.tsx
> chore(lint): fix lint warning for DevelopersTitle

- src/App/App.tsx
**Type: linting**
*  Unit or Functional tests are included in the PR? No
Removes lint warnings from App.tsx
> chore(lint): remove App.tsx lint warnings

- package.json
My bad, I put a devDep as dep.
> chore: relocate missing dep

- .circleci/config.yml
- .github/workflows/main.yml
**Type:**
Move E2E from CircleCi to GitHub Actions
> chore: add e2e to main ci

- src/pages/Version/DetailSidebar/Dist/Dist.tsx
- src/pages/Version/DetailSidebar/Dist/__snapshots__/Dist.test.tsx.snap
- src/pages/Version/DetailSidebar/Dist/styles.ts
- tools/webpack.dev.config.babel.js
Resolves https://github.com/verdaccio/ui/issues/597
> fix: package detail sidebar overflow

- src/pages/Version/DetailContainer/Readme/Readme.tsx
- src/pages/Version/DetailContainer/Readme/__snapshots__/Readme.spec.tsx.snap
> fix: markdown lists don't render bullet points

- i18n/config.ts
- i18n/translations/cs-CZ.json
- i18n/translations/de-DE.json
- i18n/translations/en-US.json
- i18n/translations/es-ES.json
- i18n/translations/fi-FI.json
- i18n/translations/fr-FR.json
- i18n/translations/ja-JP.json
- i18n/translations/km-KH.json
- i18n/translations/pt-BR.json
- i18n/translations/ru-RU.json
- i18n/translations/tr-TR.json
- i18n/translations/uk-UA.json
- i18n/translations/zh-CN.json
- i18n/translations/zh-TW.json
- src/App/Header/LanguageSwitch.tsx
- src/components/Icons/Finnish.svg
- src/components/Icons/Finnish.tsx
- src/components/Icons/index.ts
follow up of https://github.com/verdaccio/ui/pull/616
> feat: add finnish language support

- src/pages/Version/DetailContainer/UpLinks/__snapshots__/UpLinks.test.tsx.snap
- src/providers/API/APIProvider.tsx
Update login endpoint url, if you rely on this UI please upgrade accordingly
> feat: update login endpoint

- src/providers/API/APIProvider.tsx
> fix: endpoints double slash
