verdaccio/ui

- src/webui/utils/cli-utils.js
> fix: there can be no spaces between scope and registry

- test/unit/utils/package.spec.js
Test formatDateDistance with a date which is about 2 months in the past and another which is exactly 2 months in the past.
**Type:**
unit tests
*
The `formatDateDistance` test was using a date which was exactly 2 months ago so `about 2 months` is not correct but `2 months`. I have added another case where this is `about 2 months` as expected to cover both cases.
> test: fix formatDateDistance test

- tools/webpack.dev.config.babel.js
**Type:**
dev stack
this object `__UI_OPTIONS` will replace the other variables, it is easier to scale adding new properties.
I'll extend the info in a future document about plugins.
Due to this object was missing, the `yarn dev:web` was broken.
> chore: add missing __UI_OPTIONS

- src/webui/app.js
**fix:**
Non-public packages not included in the package-list after login.
A login forces react to reload the list of available packages (by changing the state).
However the state (which triggers react to refresh) is set before storing the login token resulting in fetching (XHR GET) only the public packages as the token is not yet available in the GET request.
Fixed by setting the storage items ('username' and 'token') before this.setLoggedUser().
Resolves #72
> fix: fixed failed to load all packages after login

- src/components/Dependencies/Dependencies.tsx
**Type:** Refactor typescript warnings
*  There is a related issue - #74 
Following on from #77, this PR resolves the `@typescript-eslint/no-explicit-any` rule on withRouter().
**Resolves:** #74
> fix: @typescript-eslint/no-explicit-any

- package.json
- src/history.ts
- src/router.tsx
- src/utils/url.test.ts
- src/utils/url.ts
- yarn.lock
**Type:** bugfix
*  There is a related issue? #76 
*  Unit or Functional tests are included in the PR - YES
As described in the attached issue 76, download tarball files were not showing for localhost as it is not TLD.
Also, in this PR we refactor url.ts and history.ts by removing unused functions and files being called once only.
**Resolves** #76
> fix: 76 download button hidden for localhost

- .stylelintrc
- src/App/styles.ts
- src/components/ActionBar/styles.ts
- src/components/Author/styles.ts
- src/components/AutoComplete/styles.tsx
- src/components/CopyToClipBoard/styles.ts
- src/components/Dependencies/styles.ts
- src/components/DetailContainer/styles.ts
- src/components/DetailSidebar/styles.ts
- src/components/Developers/styles.ts
- src/components/Dist/styles.ts
- src/components/Engines/styles.ts
- src/components/Footer/styles.ts
- src/components/Header/styles.ts
- src/components/Help/styles.ts
- src/components/Icon/styles.ts
- src/components/Install/styles.ts
- src/components/Layout/Layout.tsx
- src/components/Login/styles.ts
- src/components/NotFound/styles.ts
- src/components/Package/styles.ts
- src/components/RegistryInfoContent/styles.ts
- src/components/RegistryInfoDialog/styles.ts
- src/components/Repository/styles.ts
- src/components/Spinner/styles.ts
- src/components/Tag/styles.ts
- src/components/UpLinks/styles.ts
- src/components/Versions/styles.ts
- src/pages/version/styles.ts
**Type:** refactor
*  There is a related issue? **Yes**
*  Unit or Functional tests are included in the PR **No**
**Description:** First part of #97. This PR includes:
- Disable `no-empty-source` stylelint rule to not fail in some styles.ts files that will not contain templates
- Move the more simple CSS templates to objects
- Start with part of cascaded CSS templates, those that don't contains variadic parts on the selectors
Important note: There is 2 components that follows the last pattern. We cannot move them to the object syntax without changing the css-hash, so test must be updated. I prefer to put them in other PR where we are going to change some patterns (like cascaded css calls in a css template) that requires to update tests
> Part of 97 - Unify Emotion CSS format

- src/utils/api.test.ts
- src/utils/api.ts
Also prevents non .tgz requests from being handled as tgz requests — the previous if condition was incorrect
**Type:** bug
*  Unit or Functional tests are included in the PR? Yes
Previously if for whatever reason an API request resulted in a 400 error without a content-type header, then this code would fail, as it was trying to call `includes` on `null`, resulting in what looked like a [plugin/configuration error](https://github.com/bufferoverflow/verdaccio-gitlab/issues/82). Additionally, I noticed in testing that the check for handling `.tgz` files was incorrect, and it should've been `request.url.includes('.tgz') === true` rather than `!== null`, though I'm not sure the best way to test that.
> fix(api): correctly handle responses with missing content-type header

- src/components/Search/Search.test.tsx
- src/components/Search/Search.tsx
- src/pages/Version/Version.test.tsx
- src/utils/calls.ts
**Type:** bug
Headers should be part of the options if we override options.
https://github.com/verdaccio/ui/issues/118
Resolves #118
> fix: missing headers on search endpoint with token

- .yarnrc
- tools/webpack.config.js
**Type:** bug
it populates CSS url() props with `ToReplaceByVerdaccio` which cannot be replaced anyway, this PR remove that string.
https://github.com/verdaccio/ui/issues/108
Resolves #108
> fix: remove ToReplaceByVerdaccio #108

- src/components/Package/Package.tsx
- src/components/Package/styles.ts
__Type:__
bug
__Description:__
This should fix unwanted hover in PackageItem's author section.
__Notes:__
The issue here is that `PackageListItem` has the prop button as `true`, but if I removed that or set to 'false' type-script complains that the button prop should be always set to `true`.
I don't have many experiences with the type-script, but I suppose that this issue is from the `material-ui` types.
I came to with workaround but maybe there will be exist something better.
close #135
> fix(ui):  fix the hover effect on the packageItem's author area

- src/index.tsx
**Type:**
_The following has been addressed in the PR:_
This PR removes a warning in the dev environment.
The `module.accept` method was called with a different casing with resulted in a warning in the console :)
> fix: warning about modules with names differing in casing

- src/utils/login.test.ts
This PR re-adds an explicit `null` test for `isTokenExpire` which got lost in https://github.com/verdaccio/ui/pull/157.
> chore: readded null check

- package.json
- src/App/App.test.tsx
- src/App/App.tsx
- src/App/AppError.tsx
- src/components/AvatarTooltip/AvatarTooltip.tsx
- src/components/CopyToClipBoard/CopyToClipBoard.test.tsx
- src/components/CopyToClipBoard/CopyToClipBoard.tsx
- src/components/Engines/Engines.tsx
- src/components/Footer/Footer.test.tsx
- src/components/Login/Login.tsx
- src/index.tsx
- src/pages/Version/Version.tsx
- src/utils/calls.ts
- src/utils/package.ts
- src/utils/url.ts
- tsconfig.strict.json
This PR adds explicit type information to places that have been implicitly any.
No actual code changes, just improved typings in various places.
Compiling with `noImplicityAny` is now down to double digits 🎉
> Improved Typings

- package.json
- src/components/Dependencies/Dependencies.test.tsx
- src/components/Dependencies/Dependencies.tsx
- types/packageMeta.ts
- yarn.lock
**Type:** refactor
*  There is a related issue? #116 
*  Unit or Functional tests are included in the PR Yes
Moves `<Dependencies />` to Function Component syntax.
> Refactor: Dependencies - Replaced with func. comp

- src/components/Header/HeaderMenu.tsx
- src/components/Header/HeaderRight.tsx
- src/components/Header/HeaderToolTip.tsx
- src/components/Header/HeaderToolTipIcon.tsx
- src/muiComponents/Avatar/Avatar.tsx
- src/muiComponents/Button/Button.tsx
- src/muiComponents/IconButton/IconButton.tsx
- src/muiComponents/TextField/TextField.tsx
- src/muiComponents/Tooltip/Tooltip.tsx
**The following has been addressed in the PR:**
There is no issue
I fixed some imports and function's name
> Fixed minor issues

- src/components/Header/HeaderMenu.tsx
- src/components/Header/HeaderToolTipIcon.tsx
**Type:** Fix
**The following has been addressed in the PR:** There is no issue for this PR
Fixed Icon Button imports. Every mui components used should be imported from the muiComponents folder.
> Fix: Fixed imports - Icon Button

- .github/workflows/main.yml
**Type:**
CI
*  Unit or Functional tests are included in the PR No
This PR fixes the following issue:
> Input 'version' has been deprecated with message: The version property will not be supported after October 1, 2019. Use node-version instead
> ci: use node-version

- package.json
- src/components/AutoComplete/AutoComplete.tsx
- src/components/Search/Search.tsx
- yarn.lock
This PR adds typings for the react-autosuggest component.
As far as I see this is the last 3rd party component where types were missing.
No actual code changes were necessary. 🎉
> Added typings for react-autosuggest component

- package.json
**Type:** chore
*  Unit or Functional tests are included in the PR No
**Description:** @types/react-autosuggest was defined as dependency instead of be in devDependency list
> chore(deps): remove types from dependencies

- src/components/CopyToClipBoard/CopyToClipBoard.test.tsx
- src/utils/cli-utils.test.ts
*  There is a related issue? Hacktoberfest #1461
*  Unit or Functional tests are included in the PR Yes
- Helps Resolve #1461
- CopyToClipBoard.test.tsx was testing too much, so moved logic of testing to the utility file
> refactor: copyToClipBoard.test, moved test of utility to it's own test

- src/components/Search/Search.tsx
- src/utils/api.test.ts
- src/utils/api.ts
- src/utils/calls.ts
This PR removes some `ts-ignore` instructions that where placed around the`API` class.
No actual code changes, just more streamlined typings, even though I would like to rewrite the API class with async/await syntax later. But since there is nothing wrong with the actual promised based code I didn't for this PR.
> Improved Typings for API class

- src/components/Dependencies/styles.ts
- src/components/DetailSidebar/DetailSidebar.tsx
- src/components/Help/styles.ts
- src/components/NotFound/styles.ts
- src/muiComponents/Card/Card.tsx
- src/muiComponents/Card/index.ts
**The following has been addressed in the PR:** #162
Wrapped Material UI Card Component with ForwardRef.
> Card Component - Introduced ForwardRef

- jest/unit/components/__mocks__/token.ts
- package.json
- src/utils/package.ts
- yarn.lock
**Type:** build
date-fns@2
Resolves #232
> update date fns to v2

- .babelrc
**Type:** Fix
The tests were not passing, because  the emotion plugin was not defined in the` .babelrc`. Please see the error below:
> Fix: fixed tests errors

- src/components/DetailSidebar/DetailSidebar.tsx
- src/components/DetailSidebar/DetailSidebarFundButton.test.tsx
- src/components/DetailSidebar/DetailSidebarFundButton.tsx
**Type:** bug
*  There is a related issue? yes
*  Unit or Functional tests are included in the PR 
- fix the bug
- use the `context` as the other components in the same parent ( for consistence )
Resolves #410
> fix: remove prevent default and use react context

- src/utils/api.ts
> chore(api): Fixed a minor typo

- i18n/config.ts
- i18n/translations/de-AT.json
- i18n/translations/de-DE.json
- i18n/translations/en-US.json
- i18n/translations/es-ES.json
- i18n/translations/pt-BR.json
- src/App/load-dayjs-locale.ts
- tools/webpack.dev.config.babel.js
**Type:** feat
follow up of https://github.com/verdaccio/ui/pull/432
> feat(de-translations): added de-DE translations to the UI

- src/App/__snapshots__/App.test.tsx.snap
- src/components/ActionBar/ActionBarAction.tsx
- src/components/ActionBar/__snapshots__/ActionBar.test.tsx.snap
- src/components/DetailSidebar/DetailSidebarFundButton.tsx
- src/components/Footer/styles.ts
- src/components/Header/HeaderMenu.tsx
- src/components/Header/__snapshots__/Header.test.tsx.snap
- src/components/Header/styles.ts
- src/components/Icon/styles.ts
- src/components/LoginDialog/LoginDialogHeader.tsx
- src/components/NotFound/NotFound.tsx
- src/components/Package/styles.ts
- src/design-tokens/theme.ts
- src/muiComponents/MenuItem/MenuItem.tsx
closes: https://github.com/verdaccio/ui/issues/453
> ref(styles): Updated dark colors

- i18n/config.ts
- i18n/translations/en-US.json
- i18n/translations/fr-FR.json
- src/App/load-dayjs-locale.ts
**Type:** translation
*  Unit or Functional tests are included in the PR: No
Adds french translation and fixes minor mistakes in english translation
> feat: Add french language + minor english language fix

- src/utils/package.test.ts
- src/utils/package.ts
**Type: translate**
* fix, the time format is not localized at package list.
No
Yes, It bit fixed due to time format changed
Verdaccio configure `TIME FORMAT` to `DD.MM.YYYY, HH:mm:ss`, but actually the date time format is strongly depend to language.
ex(day.js localization) ...
in English: `MM/DD/YYYY HH:MM:SS A`
in French: `DD/MM/YYYY HH:MM:SS`
in German: `DD.MM.YYYY HH:MM:SS`
in Japanese: `YYYY/MM/DD HH:MM:SS`
day.js has [localized format plugin](https://day.js.org/docs/en/plugin/localized-format) which solve date time format localization problem like above.
In this PR, use it to localize date time in package list and also contains fix tests for …
> fix: time format localization

- src/template/index.html
- tools/webpack.prod.config.babel.js
**Type:** bug
*  There is a related issue? https://github.com/verdaccio/ui/pull/463
This reverts commit 4713dea3 to unblock deployments
Unfortunately the merge contains a bug, we need to try again
https://github.com/verdaccio/verdaccio/pull/1787#pullrequestreview-421269464
> fix: revert custom favicon (#463)

- i18n/config.ts
- i18n/translations/de-DE.json
- i18n/translations/en-US.json
- i18n/translations/es-ES.json
- i18n/translations/fr-FR.json
- i18n/translations/ja-JP.json
- i18n/translations/km-KH.json
- i18n/translations/pt-BR.json
- i18n/translations/uk-UA.json
- i18n/translations/zh-CN.json
- i18n/translations/zh-TW.json
- package.json
- src/App/__snapshots__/App.test.tsx.snap
- src/components/Footer/Footer.tsx
- src/components/Footer/__snapshots__/Footer.test.tsx.snap
- src/components/Icon/Icon.tsx
- src/components/Icon/img/taiwan.svg
- src/components/LanguageSwitch/LanguageSwitch.tsx
- src/design-tokens/load-dayjs-locale.ts
feat(lang): add chinese traditional language for Taiwanese
Type: translation
There is a related issue?
NO
Unit or Functional tests are included in the PR
NO
Description: Add Chinese Traditional translations for Taiwanese (zh-TW)
> feat: add chinese trad for taiwan translations

- src/design-tokens/theme.ts
-->
**Type:** bug
Resolves #478 - Registry Info window has wrong header style in Dark mode
I tried multiple colors, so no other components break with this change (see https://github.com/verdaccio/ui/issues/478#issuecomment-643599923).
> fix: error on header color in dark mode #478

- src/components/AutoComplete/AutoComplete.tsx
- src/components/AutoComplete/styles.tsx
This PR makes `AutoComplete.tsx` compatible with TypeScripts `strict` mode.
Unfortunately I had to introduce a `@ts-ignore` directive in 1 place since the provided `RenderInputComponent<T>` type does not allow to specify custom input props which we make use of. See here: https://github.com/moroshko/react-autosuggest#input-props-prop
The first generic in `RenderInputComponent<T>` only models the Suggestion, so there is currently no way to type custom input props. Ideally in the future it will allow a 2nd generic that allows you to model them like `RenderInputComponent<Suggestion, CustomInputProps>`.
I already specified the custom input prop that would need to be used: `type CustomInputProps = Pick<Props, 'disableUnderline' | 'startAdornment'>;`
So once this is fixed we can remove the …
> Feature: Strict Typing for AutoComplete Component

- package.json
- src/App/Header/Header.tsx
- src/App/Header/HeaderRight.tsx
- src/App/Header/LoginDialog/LoginDialog.tsx
- src/pages/Version/VersionContextProvider.tsx
- src/utils/api.test.ts
- src/utils/api.ts
- src/utils/calls.ts
- tsconfig.json
- tsconfig.strict.json
- yarn.lock
This PR removes the `"noImplicitAny": false` option from `tsconfig.json`.
Meaning the source code is now compatible with the Typescript `strict` setting, providing the highest type safety. 🎉 
To enable this I had to slightly adapt the ajax code, since it wasn't possible to type the existing code without introducing too many changes.
`API.request` can return a string, json or a blob based on the response content type or url ending or void if those checks don't match.
This proved to be a quite difficult scenario to type, so as to avoid too many changes to the existing code, `API.request` now returns a string (the response bodys string) where it would have previously returned `undefined`. This allowed for only minimal changes to the existing ajax code.
However the type safety in this part is …
> Refactor: Enabled typescript strict mode

- src/App/Footer/Footer.tsx
The India flag was missing and the Nicaragua flag was duplicated.
> fix(ui): Fix duplicate country flag

- src/pages/Version/DetailSidebar/Developers/Developers.tsx
- src/pages/Version/DetailSidebar/Developers/get-unique-developer-values.ts
**Type:** Fix
The following has been addressed in the PR: https://github.com/verdaccio/ui/issues/458
**Description:** The Sidebar Maintainers/Contributors section is displayed if it comes empty []. This PR fixes the issue.
> fix(ui): Fix  sidebar - developer empty section

- src/pages/home/PackageList/Help/Help.tsx
- src/pages/home/PackageList/Help/__snapshots__/Help.test.tsx.snap
**Type:** Fix
The following has been addressed in the PR: #578
**Description:** The title when there are not packages publishes yet, show with the previous version size
> fix(ui): Change no package title size

- src/utils/sec-utils.ts
**feature**
allow deep (aka anchor,i.e. \#usage) links in the markdown of readme pages. 
*  see https://github.com/verdaccio/verdaccio/issues/1938
The underlying markdown Parser already provides header ids in the generated html code for the readme files. Unfortunately these ids are filtered by the xss module. This PR adds a onIgnoreTagAttr helper for h1, h2, ..., h9 ids so that TOC navigation and direct links to paragraphs (i.e. http://localhost:4872/-/web/detail/jquery#including-jquery ) work.
> feat: allow deep links on readme pages

- src/pages/Version/DetailContainer/UpLinks/__snapshots__/UpLinks.test.tsx.snap
- src/utils/package.ts
webpack 5 does not poliffy Node utils anymore, removing dep, `?` is enough.
> fix: isObject import

- src/App/Header/HeaderGreetings.tsx
- src/pages/Version/DetailContainer/UpLinks/__snapshots__/UpLinks.test.tsx.snap
**Type:**
Removing capitalisation from greeting label. When Verdaccio is welcoming a user based on their username, it is odd to capitalise the first letter, it is probably better to make zero assumptions about the formatting of the name rather than try and format it ourselves on the UI and simply accept whatever the auth source provides as a source of truth.
In the attached screenshot, you can see the strangeness I mention, "Imjacobclark" opposed to "imjacobclark".
> Remove capitalisation from greeting label

- .github/workflows/visual-snapshots.yml
Small improvement, it will run visual snapshots only on pull request.
We should not run external services on master that might force a release failure, furthermore we don't work on master only via pull request, thus so it won't have much impact.
> build: visual snapshots only on pull request

- src/providers/API/APIProvider.tsx
Add `/data/` in front of every endpoint that retrieve from storage.
> feat: refactor api endpoints url
